### ISSUE TITLE
cron bad file mode

### ISSUE THREAD

**Issue by salzhrani** [HausCloud/AWS-EB-SSL#14]
The cron job is failing and I find this in `/var/log/cron`
`crond[3024]: (root) BAD FILE MODE (/etc/cron.d/certbot_renew)`

not sure how to fix it

**Comment by HausCloud** [comment]
@salzhrani
Can you try adjusting the permissions to 0644 instead of +x?

**Comment by salzhrani** [comment]
I did that and made sure that line endings were unix, and it worked.

**Comment by HausCloud** [comment]
Awesome! Closing this now.
