### ISSUE TITLE
instance of Fn::GetAtt references undefined resource AWSEBLoadBalancer

### ISSUE THREAD

**Issue by tuanna-hsp** [HausCloud/AWS-EB-SSL#15]
Hi guy, thanks for the awesome setup.

Been getting this error message from CodePipeline deployment
<img width="607" alt="Screen Shot 2021-03-05 at 9 33 12" src="https://user-images.githubusercontent.com/14136939/110049809-f17c8200-7d95-11eb-94e1-1fbd3cf612c2.png">

Did everything in the README, except I did not do the `eb labs download` and `eb deploy` thing cause I'm using CodePipeline.
Mine is a simple Nodejs application running on AmazonLinux 2
```
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
```

I will investigate further but any ideas would be very helpful.

**Comment by tuanna-hsp** [comment]
First, tried to remove the `.ebextensions/single_instance.config` and the deployment succeeded.
But `https` and even `http` did not work.

**Comment by tuanna-hsp** [comment]
Trying to set the single instance setting manually from EB environment configuration.
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-types.html

**Comment by tuanna-hsp** [comment]
Got it running 🙆‍♂️

**Comment by tuanna-hsp** [comment]
My EB instance was previously configured with "Load balanced" type, and somehow the `.ebextensions/single_instance.config` was causing the error.

**Comment by HausCloud** [comment]
@tuanna-hsp 
That config file was actually to catch that specific error. Glad you got it working! Closing this now.
