### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by bmitchinson** [HausCloud/AWS-EB-SSL#4]
Hey HausCloud, thanks so much for your work on this. Additionally to @ferminhg for your writeup here: https://medium.com/@ferminmoralet/aws-elasticbeanstalk-lets-encrypt-ssl-4e266838ae11

I'm getting the following error in my logs of beanstalk, and was wondering if you could help diagnose. I have an express app that runs on port 8080. All http requests resolve fine, but attempting to use https results in a "connection_refused" error.

```

Complete!
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: devapi.grazeanalytics.com
   Type:   unauthorized
   Detail: Invalid response from
   http://devapi.grazeanalytics.com/.well-known/acme-challenge/DDEZxQ542Bej7eRWN7KqGLT0yydgNs_XxS7IXmgCRhM
   [52.26.194.93]: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta
   charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot
   GET /.well-known/"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
```

I'm confused on why this would be an issue, since my Route53 configuration contains the following: 
![image](https://user-images.githubusercontent.com/33632286/90972583-f8b9fd80-e4df-11ea-92fc-fc4f0864591a.png)

Here's a link to my currently deployment, you'll notice http resolving fine as mentioned: http://blueberrydevhttps-env.eba-3x2vcgm4.us-west-2.elasticbeanstalk.com/

Any ideas here?
Thanks again *so much* for making this process as simple as possible.

**Comment by bmitchinson** [comment]
I also have the following env variables configured: 
![image](https://user-images.githubusercontent.com/33632286/90972602-18e9bc80-e4e0-11ea-89a2-b25aa0002779.png)

**Comment by ferminhg** [comment]
Hi @bmitchinson ,  are you using express to serve the app or ningx?

Because you need to serve the app in both ports 8080, 80 to certificate it with certbot and 443 port to serve HTTPS. here more info: https://community.letsencrypt.org/t/certbot-on-port-8080/26597

In prerequisites, you can read this, if you are using express maybe you need to dig more to configure it.

`Only nginx is supported since AWS seems to be shifting towards that configuration`

**Comment by HausCloud** [comment]
@bmitchinson Any progress on fixing your express app?

EDIT: Can you provide the platform info so I can help diagnose and/or proxy config?

**Comment by bmitchinson** [comment]
@ferminhg thanks for this advice!

I am running an API behind an nginx server. I choose nginx over apache due to that note in the prerequisities. I have not configured nginx anymore than the default setup.

I'm running my app on port 8080. I'd love to configure nginx to route ports 80 and 443 to port 8080, but I thought that would happen by default.

I'm on Amazon Linux 2, running on an ElasticBeanstalk EC2 with Node 12 using default proxy config. Default detailed here but, just describes that I'm using 8080 essentially. https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/nodejs-platform-proxy.html

**Comment by bmitchinson** [comment]
It looks like all I had to do was remove the first of two URLs in that environment variable!

Now that I'm only attempting to certify the URL that's in use, and I gave time for DNS records to update, I rebuilt my environment and now it's working great! Note to future readers, when updating that URL variable, make sure it only has your alias and not a AWS link, and that if you alter the env variables, you not only wait for the environment to "reload" to apply them to your process, you "rebuild" the entire setup to make sure the changes are flushed through.

![image](https://user-images.githubusercontent.com/33632286/91861414-6548a100-ec32-11ea-8e02-c8b70cf4c9a9.png)
 
Do either of you have ko-fi links / anything where I could throw a few bucks as a thank you?

**Comment by HausCloud** [comment]
> It looks like all I had to do was remove the first of two URLs in that environment variable!
> 
> Now that I'm only attempting to certify the URL that's in use, and I gave time for DNS records to update, I rebuilt my environment and now it's working great! Note to future readers, when updating that URL variable, make sure it only has your alias and not a AWS link, and that if you alter the env variables, you not only wait for the environment to "reload" to apply them to your process, you "rebuild" the entire setup to make sure the changes are flushed through.
> 
> ![image](https://user-images.githubusercontent.com/33632286/91861414-6548a100-ec32-11ea-8e02-c8b70cf4c9a9.png)
> 
> Do either of you have ko-fi links / anything where I could throw a few bucks as a thank you?

No need. Glad this helped you out.
