### ISSUE TITLE
HTTPS breaks after changing environment variables

### ISSUE THREAD

**Issue by MahmoudKhaledAli** [HausCloud/AWS-EB-SSL#6]
Hello there,

Thanks a lot for this repository, it's been a big help. A minor issue though is when I update the values of environment variables from the aws console, HTTPS stops working. I think whatever ELB does after updating environment variables overwrites the nginx.conf file. Is this the intended behavior? In ELB there are "confighooks" which are the same "hooks" but are tied to configuration changes rather than deployments. I tried duplicating the script there and it's working but I wanted to confirm if this is the way to do it or if I should expect changing environment variables to break HTTPS.

Thanks

**Comment by HausCloud** [comment]
@MahmoudKhaledAli It isn't the intended behavior. Duplicating the script in a configuration hook works, but comes at the small cost of rerunning Certbot at each configuration change. I think an ebextension nginx configuration override after initial deploy could work. Another solution would be to have the app deployment hook save the file somewhere and have the config hook just copy that over. You're welcome to implement a solution and make a pull request!

**Comment by HausCloud** [comment]
Added hook to save nginx.conf between configuration changes
