### ISSUE TITLE
Which docker image to use (needs bash etc)

### ISSUE THREAD

**Issue by andremussche** [HausCloud/AWS-EB-SSL#7]
I tried using an alpine image (which of course doesn't contain bash), but it also fails on the bigger amazonlinux:
- FROM   alpine
- FROM   frolvlad/alpine-bash
- FROM   amazonlinux:2

I get error's like "bash not found" or "no such file":

> [ERROR] An error occurred during execution of command [app-deploy] - [RunAppDeployPostDeployHooks]. Stop running the command. Error: Command .platform/hooks/postdeploy/00_ssl_setup_certbot.sh failed with error fork/exec .platform/hooks/postdeploy/00_ssl_setup_certbot.sh: no such file or directory 

I would like to have an as minimal image as possible (no php etc) since I only need to host a golang executable.

**Comment by gasi** [comment]
@andremussche I just deployed this on an AWS Elastic Beanstalk Docker app (running Haskell), so I was in a similar situation as you where I didn’t want to use one of the specific platforms, e.g. PHP, Node.js, etc.

FWIW, I originally included `.platform` and `.ebextensions` _inside_ my application Docker image, but that was a mistake! The EB runtime didn’t find the hooks and never ran them. I realized I have to package `.platform` and `.ebextensions` inside a ZIP file _alongside_ `Dockerrun.aws.json`.

This means these hooks will run on Amazon Linux 2 which I confirmed works.

If you need a real-world example, check out: https://github.com/zoomhub/zoomhub/pull/151

@HausCloud On that note, consider your scripts to be officially tested with Docker as well! 👏 

One remaining issue I ran into was that setting the cron tab didn’t work. I did some research and using `crontab` is more suitable for interactive / human use. I adapted your script to drop a file into `/etc/conf.d` which was easy to make idempotent without having to check the existence of the command using `grep`, etc.

Thanks for putting this together. As someone else said, I almost had tears of joy at 2:55am when the lock icon appeared after hours and hours trying to get this to work! 😂 

Code: https://github.com/zoomhub/zoomhub/pull/151

**Comment by HausCloud** [comment]
@gasi Glad I could help! You're welcome to make a pull request and implement your adaptation :).
@andremussche Was gasi's answer able help you fix your issue?

**Comment by HausCloud** [comment]
@andremussche I'll assume you found your solution in a couple days and close accordingly. I encourage you to share your solution, thanks.

**Comment by andremussche** [comment]
I copied the changes done by @gasi so it works now!
https://github.com/HausCloud/AWS-EB-SSL/pull/11

(mainly bash and LF fixes)
