### ISSUE TITLE
Template error on Java

### ISSUE THREAD

**Issue by ArsenBoykanych** [HausCloud/AWS-EB-SSL#8]
Hello HausCloud, thank you for this example.

I have an issue with deploying the Java Spring app with your HTTPS configs. I have tried different solutions and platforms. I have followed the gits thread where I found this repo - https://gist.github.com/tony-gutierrez/198988c34e020af0192bab543d35a62a

**Error**: Service:AmazonCloudFormation, Message:Template error: instance of Fn::GetAtt references undefined resource AWSEBLoadBalancer
**Platform**: Corretto 11 running on 64bit Amazon Linux 2/3.1.3

**Comment by gasi** [comment]
I got the same error on the Node.js sample app. I ran `eb deploy` again and the error went away. Give it a shot!

**Comment by HausCloud** [comment]
@ArsenBoykanych Are you still having issues?

**Comment by ArsenBoykanych** [comment]
Thank you @gasi and @HausCloud . 

To be honest, I'm not using the website instead of EB CLI to deploy and init app.
So I'm just adding all files from the repo, change variables, create a zip\jar file.

Can I just upload and deploy that zip twice?

**Comment by HausCloud** [comment]
@ArsenBoykanych Sure, give it a shot. I think there is additional steps with the EB CLI if you're uploading a zip. Normally it isn't compressed and the CLI knows how to package it for deployment. Let me know how that goes.

**Comment by ArsenBoykanych** [comment]
Thanks, @HausCloud. Have troubles with init and deploy with CLI.
I prepare jar and zip files and deploy them twice with a web interface. Same error that I had before.

**Comment by ArsenBoykanych** [comment]
Unfortunately, the same result with CLI 

![image](https://user-images.githubusercontent.com/17187409/102287531-58329200-3f43-11eb-8973-d2b04c3c56ed.png)

**Comment by HausCloud** [comment]
@ArsenBoykanych Double check your configuration. Your app should not have any sort of load balancer. This project is only for single instance non-load balanced environments. Let me know if this fixes your issue.

**Comment by HausCloud** [comment]
@ArsenBoykanych Pretty sure that was your issue, please respond soon or I'll be closing this a couple days.
